# Generated by Django 6.0.2 on 2026-02-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paper_money_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
